<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" charset="UTF-8" type="text/css" href="main.css">
<meta charset="UTF-8">
</head>
<body>
    <div id="panel_header_menu">
        <p id="panel_header_menu_title">AGREEMENT WITH THE WARRANTOR OF WML SYSTEM :</p>
    </div>
Public limited company "Technobank", represented by Chairman of the Board Viktar I. Khlapitski, acting on the base of the Statute, hereinafter referred to as the Warrantor, on the one hand, and any person who has agreed by way of acceptance with the terms of the present agreement, hereinafter referred to as the Holder, on the other hand, together hereinafter referred to as the Parties, have agreed on the following:
<br><h1>1. GENERAL PROVISIONS</h1>
<br>1.1. The present agreement, hereinafter referred to as the Agreement, regulates the order of Electronic Money (EM) sale by the Warrantor to the Holder, the use of EM and its further retirement by the Warrantor.
<br>1.2. The Parties recognize documents in electronic form, composed with the help of hardware-software WebMoney Transfer system (invoices, sale-agreements, accounts), signed by the analogue of the signature and the seal, legally equivalent to the corresponding documents in a simple written form, provided the authorization is successful. The Holder is identified by an individual identification number, a key and the Holder’s password in the hardware-software WebMoney Transfer system.
<br><h1>2. SUBJECT OF THE AGREEMENT</h1>
<br>2.1. The terms of the Agreement bind the Warrantor to mancipate some amount of EM to the Holder and the Holder is bound to accept this property and to pay either cash or by cashless settlement for it. The Holder gains the right to use EM within the WebMoney Transfer system for making deals which involve paying for goods, work and services. The Holder also gains the right to use EM in other transactions which do not violate the law of the Republic of Belarus.
<br>2.2. The Warrantor undertakes an absolute and irrevocable obligation to retire the EM sold by the Warrantor to the Holder.
<br><h1>3. PROCEDURES FOR SELLING ELECTRONIC MONEY</h1>
<br>3.1. After the electronic purse, hereinafter referred to as EP, is opened the Holder purchases EM. He can do it for choice either in the branch offices of the Warrantor or from the Warrantor’s representatives. The Holder can pay either cash or by cashless settlement at the amount of principal, including the payment using the Warrantor’s prepaid cards (scratch-cards). When paying or transferring funds, the Holder has to indicate the right unique number of EM which corresponds with the number of the Agreement.
<br>3.2. EM enters into the EP of the Holder during the Warrantor’s working hours on the next working day at the latest. It appears in the same amount and currency as received by the Warrantor.
<br>3.3. EM is issued without restrictions on validity.
<br>3.4. Transfer of property rights for EM is verified by means of hardware-software WebMoney Transfer system through processing invoices, by which the Parties recognize transactions’ records. They verify the amount of EM that belongs to the Holder by the rights of property.
<br>3.5. The number of the Holder’s rights to claim in the WebMoney Transfer system is verified by the property rights for EM and is reflected in the Holder’s accounts by the use of certain amount of title units WebMoney of type B, hereinafter referred to as WMB. This amount is equivalent in cost to the amount of EM that belongs to the Holder by the rights of property.
<h1>4. PROCEDURES FOR USING ELECTRONIC MONEY</h1>
<br>4.1. The Holders have the right to use EM for payments with Merchants, which accept EM as a payment for goods and services. The Holder may also use EM for any other civil deals within the law of the Republic of Belarus.
<br>4.2. When transferring EM from EP of one Holder to the other Holder the Warrantor’s commission is deducted from the sender of EM according to the Warrantor’s tariffs.
<br>4.3. The Holders have the right to fill in and check up on the content of the information fields in the form, being used, on the electronic documents with the indicated terms of the deal (sale agreements, bills and other) within the functioning law.
<br>4.4. The present Agreement does not touch upon and does not change the terms specified by the Parties of the deal concerning terms of delivery and/or sale of goods (fulfillment of work, rendering of services), their quality and other.
<br>4.5. The Parties of the deal are responsible for the observance of norms of legislation and bank policy.
<h1>5. PROCEDURES FOR ELECTRONIC MONEY REDEMPTION BY THE WARRANTOR</h1>
<br>5.1. When the Holder produces EM for redemption the Warrantor puts it into force either by exchanging EM for cash in the Warrantor’s or his representatives’ cash registers or by transferring funds to the current and other bank accounts, specified by the Holder. The Warrantor’s commission is deducted from the receiver of the money, according to the Warrantor’s tariffs.
<br>5.2. The redemption is carried out by the Warrantor without restrictions of validity of EM.
<br>5.3. The Warrantor’s obligation of redemption is considered performed from the moment of cash payment, crediting of the Holder’s account or taking the money from the Warrantor’s account in favor of the beneficiary indicated by the Holder.
<h1>6. RIGHTS AND DUTIES OF THE WARRANTOR</h1>
<br>6.1. The Warrantor has the right:
<br>6.1.1. To interrupt the use or redemption of EM, if the fulfillment of the corresponding money request is impossible or will lead to the violation of the law or bank policy. The Warrantor will inform the Holder about the interruption of the redemption immediately, pointing out the reasons.
<br>6.1.2. To forbid the Holder to use or retire EM, when authorization is not successful or when the money request is composed, violating the rules of its composition, including the cases, when the amount of EM indicated in the money request exceeds the amount at the Holder’s disposal.
<br>6.1.3. To deduct commissions according to the Warrantor’s tariffs.
<br>6.1.4. To alter the present Agreement and the Warrantor’s tariffs. The Warrantor will inform the Holder within ten days before the alterations are put into force by putting the corresponding information in electronic form on the Warrantor’s web-server.
<br>6.1.5. To refuse to fulfill the Agreement in case of disclosure of unreliable information provided by the Holder in order to fulfill the terms of the present Agreement.
<br>6.2.  The Warrantor is obliged:
<br>6.2.1. To inform the Holder of the interruption or reactivation of the money request fulfillment.
<br>6.2.2. To keep the Holder informed about possible hazards when buying, using or retiring of EM by the Warrantor.
<br>6.2.3. To provide the observance of EM operation regulations.
<br>6.2.4. To pass the rights of property for EM to the Holder by creating transactions’ record which proves that the Holder gets the property rights for EM, received to the Holder’s identification number in the WebMoney Transfer system, within one working day from the moment of the incomings according to the Agreement.
<br>6.2.5. By the Holder’s written request to give paper copies of the acts, attested by the signature and the seal of the Warrantor’s plenipotentiary within three days after the request was made.
<h1>7. RIGHTS AND DUTIES OF THE HOLDER</h1>
<br>7.1. The Holder has the right to use EM for payments with Merchants which accept EM as a payment for goods and services. The Holder may also use EM for any other civil deals within the law of the Republic of Belarus.
<br>7.2. The Holder is obliged:
<br>7.2.1. To observe the terms of the Agreement and requirements of the WebMoney Transfer system.
<br>7.2.2. To pay commissions to the Warrantor according to the Warrantor’s tariffs.
<h1>8. LIABILITY OF THE PARTIES</h1>
<br>8.1. The Warrantor is not responsible for the damage which occurs as a result of the Holder’s violation of the rules of the Agreement.
<br>8.2. The Holder runs the hazards of the damage in case of losing control over the use of his EP.
<br>8.3. The Parties are relieved of responsibility for partial or full violation of their obligations according to the Agreement if such violation is the result of insuperable difficulties, which occurred after the Agreement was put in force and which could not be prevented by any reasonable measures.
<br>8.4. The Party is obliged to inform the other Party about emergence and termination of the influence of the insuperable difficulties which hamper the fulfillment of the obligations of the agreement. The terms of the fulfillment of the obligations is then shifted in accordance with the period of time, while those difficulties were in effect.
<br>8.5. The Warrantor is not responsible for non-observance of some terms of the deal, defined by the Parties, excluding the cases, when the Warrantor’s fault in such non-observance is proved.
<h1>9. VALIDITY PERIOD AND PROCEDURES FOR DISSOLVING THE AGREEMENT</h1>
<br>9.1. The Agreement comes into force from the moment of the Holder’s acceptance of the present Agreement in the hardware-software WebMoney Transfer System while registering a new EP.
<br>9.2. The Warrantor has the right to dissolve the Agreement in the following cases:
<br>9.2.1. When the Holder does not accept the alterations in the Agreement, including the alterations of the rules, provided that these alterations are put on the Warrantor’s web-server within ten days after they came into force. The Agreement is considered dissolved from the moment when the Warrantor gets the Holder’s notice in the order established in the present Agreement.
<br>9.2.2. In case of the Holder’s violation of the terms of the Agreement, if such violation caused damage for the Warrantor or in the Warrantor’s reasoned opinion hampered the secure functioning of EM operation regulations. The Warrantor is then obliged to inform the Holder about the violation (by electronic notification or blocking of access and other) within thirty days from the moment of the enclosure, unless there is a necessity to analyze the fact of violation and its influence on the security of EM operation regulations in general. The date and the time of the violation of the terms of the Agreement is considered the date and time of the dissolution of the Agreement, unless the Warrantor for choice sets a later date.
<br>9.3. The Holder has the right to dissolve the Agreement and send a corresponding electronic document or notification in the written form to the Warrantor. The Agreement is then considered dissolved from the moment when the Warrantor received this notification.
<br>9.4. When sending the notification about dissolution of the Agreement to the Warrantor, the Holder takes the responsibility not to perform any operations with EM and not to launch his copy of EP from the moment he sent the notification. In case of violation of this responsibility, which the Warrantor proves by the documents (electronic documents) with the analogue of the Holder’s signature, the Warrantor is freed from any responsibility to the Holder, according to the Agreement.
<br>9.5. Before sending the notification about the dissolution of the Agreement the Holder is obliged to retire all the EM at his disposal.
<h1>10. DECLARATION OF THE HOLDER</h1>
I hereby confirm that I am acquainted and agree with the terms of the present Agreement on WMB, with the Code of the WebMoney Transfer system and with the rules of making deals using electronic money. By opening an electronic purse I join the Agreement.
Please give me a permission to obtain EM to refill the electronic purse.
<h1>11. LEGAL ADDRESS AND DETAILS OF THE WARRANTOR</h1>
</body>
