<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" charset="UTF-8" type="text/css" href="main.css">
<meta charset="UTF-8">
</head>
<body>
    <div id="panel_header_menu">
        <p id="panel_header_menu_title">Информация :</p>
    </div>
<menu>
    <li>Законодательство</li>
    <li>Ответы на вопросы</li>
    <li>Кодекс системы WebMoneyTransfer</li>
    <li>Соглашение с Гарантом по WML</li>
    <li>AGREEMENT WITH THE WARRANTOR OF WMB SYSTEM</li>
    <li>Тарифы</li>
    <li>Аттестация</li>
    <li>Заявления</li>
</menu>
</body>
