<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" charset="UTF-8" type="text/css" href="main.css">
<meta charset="UTF-8">
</head>
<body>
    <div id="panel_header_menu">
        <p id="panel_header_menu_title">Меню :</p>
    </div>

<menu>
    <li>Открытие счета</li>
    <li>Внести WML</li>
    <li>Снять WML</li>
    <li>Платежи
        <menu>
            <li>Коммунальные</li>
            <li>Телефон</li>
            <li>Интернет</li>
        </menu>
    </li>
    <li>Переводы
        <menu>
            <li>В системе WMLandscape
                <menu>
                    <li>На свои счета</li>
                    <li>На чужие счета</li>
                </menu>
            </li>
            <li>В другую системе
                <menu>
                    <li>На свои счета</li>
                    <li>На чужие счета</li>
                </menu>
            </li>

        </menu>
    </li>
</menu>

</body>
