<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" charset="UTF-8" type="text/css" href="http://interactivefishing.tv/main.css">
<meta charset="UTF-8">
</head>
<body>
    <div id="panel_header_menu">
        <p id="panel_header_menu_title">Мои счета :</p>
    </div>

    <br><a id="link_red">Мои счета:</a>
    <table border="1" width="100%" cellpadding="0" cellspacing="0">
        <tr>
            <th bgcolor="#ffcaca"><a align="center" class="cell-pagetitle">Номер счета</a></th>
            <th bgcolor="#ffcaca"><a align="center" class="cell-pagetitle">Описание</a></th>
            <th bgcolor="#ffcaca"><a align="center" class="cell-pagetitle">Сумма</a></th>
            <th bgcolor="#ffcaca"><a align="center" class="cell-pagetitle">Валюта</a></th>
        </tr>

        <tr>
            <td><a class="link">4081781100200000001</a></td>
            <td><a class="link">Накопительный счет</a></td>
            <td><a class="link">10265.38</a></td>
            <td><a class="link">WML</a></td>
        </tr>
        <tr>
            <td><a class="link">4081784000100000001</a></td>
            <td><a class="link">Счет конвертирования в доллары</a></td>
            <td><a class="link">100.00</a></td>
            <td><a class="link">USD</a></td>
        </tr>
        <tr>
            <td><a class="link">4081784000100000001</a></td>
            <td><a class="link">Текущий зарплатный счет</a></td>
            <td><a class="link">670.72</a></td>
            <td><a class="link">WML</a></td>
        </tr>
        <tr>
            <td><a class="link">4081797800100000001</a></td>
            <td><a class="link">Счет конвертирования в евро</a></td>
            <td><a class="link">100.09</a></td>
            <td><a class="link">EUR</a></td>
        </tr>
        <tr>
            <td><a class="link">4081781100300000001</a></td>
            <td><a class="link">Потребительский кредит</a></td>
            <td><a class="link"> 90008.50</a></td>
            <td><a class="link">WML</a></td>
        </tr>
        <tr>
            <td><a class="link">4081781000100000001</a></td>
            <td><a class="link">Счет конвертирования в рубли</a></td>
            <td><a class="link">1003.74</a></td>
            <td><a class="link">RUR</a></td>
        </tr>
    </table>

</body>
