<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" charset="UTF-8" type="text/css" href="http://interactivefishing.tv/main.css">
<meta charset="UTF-8">
</head>
<body>
    <div id="panel_header_menu">
        <p id="panel_header_menu_title">Снять WML :</p>
    </div>
<br>    <a>Снять деньги со счета:</a><br><br>
    <form>
        <table>
        <tr>
            <td>
                <a id="link_red">Cчет:</a>
            </td>
            <td>
              <select id="idDebitAccount" name="DebitAccount" title="4081781100200000001 Накопительный счет 10265.38 WML">
                <option value="4081781100200000001" selected="" title="4081781100200000001 Накопительный счет 10265.38 WML">4081781100200000001 Накопительный счет 10265.38 WML</option>
                <option value="4081784000100000001" selected="" title="4081784000100000001 Счет конвертирования в доллары 100.00 USD">4081784000100000001 Счет конвертирования в доллары 100.00 USD</   option>
                <option value="4081784000100000001" selected="" title="4081784000100000001 Текущий зарплатный счет 670.72 WML">4081784000100000001 Текущий зарплатный счет 670.72 WML</option>
                <option value="4081797800100000001" selected="" title="4081797800100000001 Счет конвертирования в евро 100.09 EUR">4081797800100000001 Счет конвертирования в евро 100.09 EUR</option>
                <option value="4081781100300000001" selected="" title="4081781100300000001 Потребительский кредит 90008.50 WML">4081781100300000001 Потребительский кредит 90008.50 WML</option>
                <option value="4081781000100000001" selected="" title="4081781000100000001 Счет конвертирования в рубли 1003.74 RUR">4081781000100000001 Счет конвертирования в рубли 1003.74 RUR</option>
              </select>
            </td>
        </tr>
        <tr>
            <td>
                <a id="link_red">Сумма:</a>
            </td>
            <td>
                <input id="summa" name="summa" type="text" class="ui-widget-content" tabindex="1" maxlength="16"><a class="link">WML</a></input>
            </td>
        </tr>
        <tr>
           <td>
           </td>
           <td>
                <br><button id="panel_header_menu" type="submit" value="Submit">
                    <p align = "right" id="panel_header_menu_title">Снять</p>
                </button>
           </td>
        </tr>
    </form>
<body>

