<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" charset="UTF-8" type="text/css" href="http://interactivefishing.tv/main.css">
<meta charset="UTF-8">
</head>
<body>
    <div id="panel_header_menu">
        <p id="panel_header_menu_title">Заявления :</p>
    </div>

<div class="width-fix"><h1>Подключить платежную систему WML</h1>

	<div class="order-info">
	<p>Платежная система «WML» бесплатно подключается любому клиенту. Просто заполните небольшую заявку и&nbsp;вам перезвонят для подключения:</p>

	<div class="promo-block promo-block-special instruction red step1"><i class="b-icon b-promo-icon"><i class="b-icon__icon"></i></i><div class="promo-block-inner">
		<h2 class="steps__description">Я&nbsp;помню кодовое слово, указанное мной при открытии счета</h2>

		<div class="steps__btn" data-next="3">Нет<ins class="steps__btn-r"></ins></div>
		<div class="steps__btn steps__btn_with-arrow" data-next="2">Да<ins class="steps__btn-r"></ins></div>
		<div class="clear"></div>
	</div></div>

	<div class="promo-block promo-block-special instruction red step2 g-hidden"><i class="b-icon b-promo-icon"><i class="b-icon__icon"></i></i><div class="promo-block-inner">
		<h2 class="steps__description">Я&nbsp;ранее уже пользовался данной услугой</h2>

		<a href="http://localhost/notavailable.html" class="steps__btn">Нет<ins class="steps__btn-r"></ins></a>
		<div class="steps__btn steps__btn_with-arrow" data-next="4">Да<ins class="steps__btn-r"></ins></div>
		<div class="clear"></div>
	</div></div>

	<div class="promo-block promo-block-special terminal red step3 g-hidden">
        <i class="b-icon b-promo-icon"><i class="b-icon__icon"></i></i>
            <div class="promo-block-inner">
    		    <p>Если вы&nbsp;забыли кодовое слово, то&nbsp;для подключения услуги воспользуйтесь банкоматом или обратитесь в ближайшее отделение банка.</p>
	        </div>
    </div>

	<div class="promo-block promo-block-special used red step4 g-hidden">
        <i class="b-icon b-promo-icon"><i class="b-icon__icon"></i></i>
            <div class="promo-block-inner">
        		<p class="before-list">Если вы&nbsp;забыли свой логин или пароль, вам необходимо обратиться в&nbsp;Телефонный центр «Альфа-Консультант»:</p>
		
		<ul>
			
<li><nobr class="phone">+7-902-7-800-807 —</nobr> для Москвы</li>
			
<li><nobr class="phone">+7-902-7-800-807 —</nobr> для регионов</li>
		</ul>
	</div></div>

	<br>
</div>

</div>
</body>
