<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" charset="UTF-8" type="text/css" href="http://interactivefishing.tv/main.css">
<meta charset="UTF-8">
</head>
<body>
    <div id="panel_header_menu">
        <p id="panel_header_menu_title">Тарифы :</p>
    </div>

<table border="1" align="left" cellpadding="3" cellspacing="3">
<tbody><tr>
<td colspan="2" align="left" class="cell-pagetitle"><strong>Наименование услуги</strong></td>
<td width="120" align="center" class="cell-pagetitle"><strong>Тариф</strong></td>
<td width="133" align="left" nowrap="" class="cell-pagetitle">&nbsp;
  <strong>Примечание</strong>&nbsp;</td>
</tr>
<tr>
<td width="24" align="left" class="cell-pagetitle"><strong>1.</strong></td>
<td colspan="3" align="left" class="cell-pagetitle"><strong><strong><a name="tarifattestat"></a></strong>ПЕРСОНАЛИЗАЦИЯ </strong></td>
</tr>
<tr>
<td align="left" nowrap="" class="cell-pagetitle"><strong>1.1.</strong></td>
<td align="left" class="cell-pagetitle">Рассмотрение заявления на выдачу<br><strong>НАЧАЛЬНОГО АТТЕСТАТА</strong></td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">50 000<br>
белорусских рублей</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">&nbsp;</td>
</tr>
<tr>
<td align="left" class="cell-pagetitle"><strong>1.2.</strong></td>
<td align="left" class="cell-pagetitle">Рассмотрение заявления на выдачу <br>
<strong>ПЕРСОНАЛЬНОГО АТТЕСТАТА </strong>физическому лицу</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">100 000<br>
белорусских рублей</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">&nbsp;</td>
</tr>
<tr>
<td align="left" class="cell-pagetitle"><strong>1.3.</strong></td>
<td align="left" class="cell-pagetitle"> Рассмотрение заявления на выдачу <strong>АТТЕСТАТА СЕРВИСА</strong> WebMoney юридическому лицу и индивидуальному предпринимателю</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">900 000<br>
белорусских рублей</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">&nbsp;</td>
</tr>
<tr>
<td align="left" class="cell-pagetitle"><strong>2.</strong></td>
<td colspan="3" align="left" class="cell-pagetitle"><strong>ПРОДАЖА</strong> банком ЭЛЕКТРОННЫХ ДЕНЕГ<br>
(1 единица электронных денег (WMB) = 1 белорусскому рублю) </td>
</tr>
<tr>
<td align="left" class="cell-pagetitle"><strong>2.1.</strong></td>
<td align="left" class="cell-pagetitle">В кассах головного отделения ОАО «Технобанк»</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">3%<br></td>
<td rowspan="5" align="left" bgcolor="#ffcaca" class="cell-pagetitle"><div align="center">сумма тарифа округляется до 10</div></td>
</tr>
<tr>
<td align="left" class="cell-pagetitle"><strong>2.2.</strong></td>
<td align="left" class="cell-pagetitle">Через кассы, банкоматы, инфокиоски и устройства самообслуживания других банков</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">3%<br>
от суммы</td>
</tr>
<tr>
<td align="left" class="cell-pagetitle"><strong>2.3.</strong></td>
<td align="left" class="cell-pagetitle">Через РУП «Белпочта»</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">3%<br>
от суммы</td>
</tr>
<tr>
<td align="left" class="cell-pagetitle"><strong>2.4.</strong></td>
<td align="left" class="cell-pagetitle">Посредством скретч-карт ОАО «Технобанк»</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">3%<br>от суммы</td>
</tr>
<tr>
<td align="left" class="cell-pagetitle"><strong>2.5.</strong></td>
<td align="left" class="cell-pagetitle">За безналичные белорусские рубли </td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">3%<br>от суммы</td>
</tr>
<tr>
<td align="left" class="cell-pagetitle"><strong>3.</strong></td>
<td colspan="3" align="left" class="cell-pagetitle"><strong>ПОКУПКА</strong> банком ЭЛЕКТРОННЫХ ДЕНЕГ физических лиц <br>
(1 единица электронных денег (WMB) = 1 белорусскому рублю)</td>
</tr>
<tr>
<td align="left" class="cell-pagetitle"><strong>3.1.</strong></td>
<td align="left" class="cell-pagetitle">За наличные белорусские рубли</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">&nbsp;</td>
<td rowspan="8" align="left" bgcolor="#ffcaca" class="cell-pagetitle"><div align="center">
  <p>сумма тарифа округляется до 10 </p>
  </div></td>
</tr>
<tr>
<td align="left" class="cell-pagetitle">&nbsp;</td>
<td align="left" class="cell-pagetitle">а) с формальным аттестатом </td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle style5"><p><b><u>8%</u></b><br>
  от суммы</p></td>
</tr>
<tr>
<td align="left" class="cell-pagetitle">&nbsp;</td>
<td align="left" class="cell-pagetitle">б) с начальным аттестатом </td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle style5"><p><b><u>5%</u></b><br>
  от суммы</p></td>
</tr>
<tr>
<td align="left" class="cell-pagetitle">&nbsp;</td>
<td align="left" class="cell-pagetitle">в) с персональным аттестатом </td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle style5"><p><b><u>3%</u></b><br>
  от суммы</p></td>
</tr>
<tr>
<td align="left" class="cell-pagetitle"><strong>3.2.</strong></td>
<td align="left" class="cell-pagetitle">За безналичные белорусские рубли с перечислением (без открытия счета) на счет клиента:</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">&nbsp;</td>
</tr>
<tr>
<td align="left" class="cell-pagetitle">&nbsp;</td>
<td align="left" class="cell-pagetitle">а) в ОАО «Технобанк»</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle style5"><p><b><u>1.99%</u></b><br>
  от суммы,<br>
  если иное не предусмотрено договором</p></td>
</tr>
<tr>
<td align="left" class="cell-pagetitle">&nbsp;</td>
<td align="left" class="cell-pagetitle">б) в другом банке Республики Беларусь</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">3,2%<br>
от суммы<br>
(min 20 000 белорусских рублей),
<p>если иное не предусмотрено договором </p></td>
</tr>
<tr>
<td align="left" class="cell-pagetitle">&nbsp;</td>
<td align="left" class="cell-pagetitle">в) за пределы Республики Беларусь (минимальная сумма 1&nbsp;000&nbsp;000 белорусских рублей) </td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">300 000 белорусских рублей    (min 1&nbsp;000&nbsp;000 белорусских рублей)</td>
</tr>
<tr>
<td align="left" class="cell-pagetitle"><strong>4.</strong></td>
<td align="left" class="cell-pagetitle"><strong>ПЕРЕВОД</strong> ЭЛЕКТРОННЫХ ДЕНЕГ<br>
(платеж на кошелек с отличным от кошелька отправителя идентификационным номером WMID)</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">0,8%<br>от суммы транзакции<br>(min 0.01 WMB, max 105&nbsp;000 WMB)</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">&nbsp;</td>
</tr>
<tr>
<td align="left" class="cell-pagetitle"><strong>5.</strong></td>
<td align="left" class="cell-pagetitle"><strong>РОЗЫСК</strong> <br>
(по инициативе клиента)<br>
ошибочно перечисленных электронных денег</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">6 000<br>
белорусских рублей</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">&nbsp;</td>
</tr>
<tr>
<td align="left" class="cell-pagetitle"><strong>6.</strong></td>
<td colspan="3" align="left" class="cell-pagetitle"><strong>ВЫПИСКА </strong>операций по электронному кошельку:
  <p>&nbsp;</p></td>
</tr>
<tr>
<td align="left" class="cell-pagetitle"><strong>6.1.</strong></td>
<td colspan="3" align="left" class="cell-pagetitle">Для физических лиц:</td>
</tr>
<tr>
<td align="left" class="cell-pagetitle">&nbsp;</td>
<td align="left" class="cell-pagetitle">а) Единоразовая за день</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">2 000<br>
белорусских рублей</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">&nbsp;</td>
</tr>
<tr>
<td align="left" class="cell-pagetitle">&nbsp;</td>
<td align="left" class="cell-pagetitle">б) Единоразовая за период до месяца </td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">4 000<br>
белорусских рублей</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">&nbsp;</td>
</tr>
<tr>
  <td align="left" class="cell-pagetitle">&nbsp;</td>
  <td align="left" class="cell-pagetitle">в) Единоразовая за месяц </td>
  <td align="left" bgcolor="#ffcaca" class="cell-pagetitle">6 000<br>
    белорусских рублей</td>
  <td align="left" bgcolor="#ffcaca" class="cell-pagetitle"><p align="center">&nbsp;</p>
      <p align="center">&nbsp;</p></td>
</tr>

<tr>
  <td align="left" class="cell-pagetitle">&nbsp;</td>
  <td align="left" class="cell-pagetitle">г) Единоразовая за период свыше месяца </td>
  <td align="left" bgcolor="#ffcaca" class="cell-pagetitle">6 000<br>
    белорусских рублей за каждый месяц </td>
  <td align="left" bgcolor="#ffcaca" class="cell-pagetitle"><p align="center">Выписка операций за период более 3-х месяцев предоставляется без указания назначения платежа </p>    </td>
</tr>
<tr>
  <td align="left" class="cell-pagetitle"><strong>6.2.</strong></td>
  <td colspan="3" align="left" class="cell-pagetitle">Для юридических лиц и индивидуальных предпринимателей:</td>
</tr>
<tr>
  <td align="left" class="cell-pagetitle">&nbsp;</td>
  <td align="left" class="cell-pagetitle">а) Единоразовая за день</td>
  <td align="left" bgcolor="#ffcaca" class="cell-pagetitle">3 000<br>
    белорусских рублей</td>
  <td align="left" bgcolor="#ffcaca" class="cell-pagetitle">&nbsp;</td>
</tr>
<tr>
  <td align="left" class="cell-pagetitle">&nbsp;</td>
  <td align="left" class="cell-pagetitle">б) Единоразовая за период до месяца </td>
  <td align="left" bgcolor="#ffcaca" class="cell-pagetitle">5 000<br>
    белорусских рублей</td>
  <td align="left" bgcolor="#ffcaca" class="cell-pagetitle">&nbsp;</td>
</tr>
<tr>
  <td align="left" class="cell-pagetitle">&nbsp;</td>
  <td align="left" class="cell-pagetitle">в) Единоразовая за месяц </td>
  <td align="left" bgcolor="#ffcaca" class="cell-pagetitle">8 000<br>
    белорусских рублей</td>
  <td align="left" bgcolor="#ffcaca" class="cell-pagetitle"><p align="center">&nbsp;</p>      </td>
</tr>
<tr>
  <td align="left" class="cell-pagetitle">&nbsp;</td>
  <td align="left" class="cell-pagetitle">г) Единоразовая за период за период свыше месяца </td>
  <td align="left" bgcolor="#ffcaca" class="cell-pagetitle">8 000<br>
    белорусских рублей за каждый месяц </td>
  <td align="left" bgcolor="#ffcaca" class="cell-pagetitle"><p align="center">Выписка операций за период более </p>
    <p align="center">3-х месяцев предоставляется без указания назначения платежа </p>
    <p align="center"></p></td>
</tr>

<tr>
<td align="left" class="cell-pagetitle"><strong>7.</strong></td>
<td align="left" class="cell-pagetitle">Внесение изменений в реквизиты платежа при покупке/продаже банком электронных денег (по заявлению клиента)</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">1% от суммы платежа</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle"><div align="center">сумма тарифа округляется до 10 </div></td></tr>
<tr>
<td align="left" class="cell-pagetitle"><strong>8.</strong></td>
<td align="left" class="cell-pagetitle">Заверка копии чека, подтверждающего совершение операции WMB  (по заявлению клиента)</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">3 000<br>
белорусских рублей</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">&nbsp;</td>
</tr>
<tr>
<td align="left" class="cell-pagetitle"><strong>9.</strong></td>
<td align="left" class="cell-pagetitle">Восстановление реквизитов скретч-карты, поврежденных по вине Держателя </td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">5 000<br>
белорусских рублей</td>
<td align="left" bgcolor="#ffcaca" class="cell-pagetitle">&nbsp;</td>
</tr></tbody></table>
</body>
