<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" charset="UTF-8" type="text/css" href="http://interactivefishing.tv/main.css">
<meta charset="UTF-8">
</head>
<body>
    <div id="panel_header_menu">
        <p id="panel_header_menu_title">Ответы на запросы :</p>
    </div>

<h1>На рассмотрении:</h1>
<h2>За месяц:</h2>
Нет
<h2>Все:</h2>
Нет
<h1>Обсуждение:</h1>
<h2>За неделю:</h2>
Нет
<h2>Все:</h2>
Нет
<h1>Закрытые:</h1>
<h2>За месяц:</h2>
Нет
<h2>Все:</h2>
Нет

</body>
